name: ClawBar
options:
  bundleIdPrefix: com.vector.clawbar
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

packages:
  ClawBarCore:
    path: Packages/ClawBarCore

targets:
  ClawBar:
    type: application
    platform: macOS
    sources:
      - path: Packages/ClawBarCore/Sources
      - path: ClawBar/Assets.xcassets
    dependencies: []
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vector.clawbar
        PRODUCT_NAME: ClawBar
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        INFOPLIST_FILE: ClawBar/Info.plist
        CODE_SIGN_ENTITLEMENTS: ClawBar/ClawBar.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ENABLE_HARDENED_RUNTIME: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
